<?php

namespace AppBundle\Repository;
use Doctrine\ORM\AbstractQuery;

/**
 * CommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeRepository extends \Doctrine\ORM\EntityRepository
{
    use UtilForRepository;

    private function getMinSelectDql(){
        $dql  = "SELECT c from AppBundle:Commande c ";
        return $dql;
    }
    private function getMainDql(){
        $dql  = "SELECT c,l,r,d,p from AppBundle:Commande c
                  JOIN c.livraison l
                  JOIN c.restaurant r ";
        return $dql;
    }
    public function findAll(){

        $dql = $this->getMinSelectDql();
        $query = $this->getEntityManager()
            ->createQuery($dql);
        return $query->getResult();
    }

    public function findByRestaurant($idRestaurant=''){
        $dql = $this->getMainDql();

        $dql  = $dql. " LEFT JOIN c.detailCommandes d
                        JOIN d.plat p
                        WHERE r.id LIKE :idRestaurant
                        ORDER BY c.dateCommande DESC";
        return $this->fillParameterAndGetResult($dql,array('idRestaurant'=>$idRestaurant));
    }

    public function findByUser($idUser){
        $dql = $this->getMinSelectDql();
        $dql = $this->addColumn($dql,'r');
        $dql  = $dql. "JOIN c.user u
                  JOIN c.restaurant r
                  WHERE u.id LIKE :idUser
                  ORDER BY c.dateCommande DESC";

        return $this->fillParameterAndGetResult($dql,array('idUser'=>$idUser));
    }
}
