<?php

namespace AppBundle\Repository;

/**
 * LivreurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LivreurRepository extends \Doctrine\ORM\EntityRepository
{
    private function getMainDql(){
        $dql  = "SELECT l
                  from AppBundle:Livreur l";
        return $dql;
    }
    public function findAll(){

        $dql = $this->getMainDql();
        $query = $this->getEntityManager()
            ->createQuery($dql);
        return $query->getArrayResult();
    }

    public function findFree(){
        $dql = "SELECT l from AppBundle:Livreur l WHERE l.isFree=:isFree";

        $query = $this
            ->getEntityManager()
            ->createQuery($dql)
            ->setParameter('isFree',true);

        return $query->setMaxResults(1)->getOneOrNullResult();
    }
}
