<?php

namespace AppBundle\Repository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
    use UtilForRepository;
    private function getMainDql(){
        $dql  = "SELECT p,r,i,q,c
                  from AppBundle:Plat p
                  JOIN p.restaurant r
                  JOIN r.quartier q
                  JOIN q.commune c
                  LEFT JOIN p.image i";
        return $dql;
    }
    public function findAll(){

        $dql = $this->getMainDql();
        $query = $this->getEntityManager()
            ->createQuery($dql);
        return $query->getArrayResult();
    }

    public function findOnMenu(){
        $dql = $this->getMainDql();
        $dql = $dql." WHERE p.onMenu=:onMenu";

        return $this->fillParameterAndGetResult($dql,array('onMenu'=>true));
    }

    public function findByRestaurant($idRestaurant=''){
        $dql = $this->getMainDql();
        $dql = $dql." WHERE r.id LIKE :idRestaurant";

        return $this->fillParameterAndGetResult($dql,array('idRestaurant'=>$idRestaurant));
    }


}
