<?php

namespace AppBundle\Repository;

/**
 * PlatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlatRepository extends \Doctrine\ORM\EntityRepository
{
    use UtilForRepository;

    private function mainQueryBuilder(){
        $queryBuilder = $this->createQueryBuilder('p')
            ->addSelect(['r','ir','q','c','ip'])
            ->leftJoin('p.restaurant','r')
            ->leftJoin('r.imageRestaurants','ir')
            ->leftJoin('r.quartier','q')
            ->leftJoin('q.commune','c')
            ->leftJoin('p.imagePlat','ip');

        return $queryBuilder;
    }
    public function findAll(){
        return $this->mainQueryBuilder()
            ->getQuery()
            ->getArrayResult();    }

    public function findOnMenu(){

        return $this->mainQueryBuilder()
            ->where('p.onMenu=:onMenu')
            ->setParameter('onMenu',true)
            ->getQuery()
            ->getArrayResult();
    }

    public function findByRestaurant($idRestaurant=''){

        return $this->mainQueryBuilder()
            ->where('r.id LIKE :idRestaurant')
            ->setParameter('idRestaurant',$idRestaurant)
            ->getQuery()
            ->getArrayResult();
    }

    public function findById($id){

        $plat = $this->mainQueryBuilder()
            ->where('p.id LIKE :id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getArrayResult();

        return count($plat)===1?$plat[0]:null;
    }

}
