<?php

namespace AppBundle\Repository;

/**
 * QuartierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuartierRepository extends \Doctrine\ORM\EntityRepository
{
    private function getMainDql(){
        $dql  = "SELECT q,c
                  from AppBundle:Quartier q
                  JOIN q.commune c";
        return $dql;
    }
    public function findAll(){

        $dql = $this->getMainDql();
        $query = $this->getEntityManager()
            ->createQuery($dql);
        return $query->getArrayResult();
    }

}
