<?php

namespace AppBundle\Repository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends \Doctrine\ORM\EntityRepository
{
    private function getMainQuery(){
        $dql  = "SELECT r,q,c from AppBundle:Restaurant r
                  JOIN r.quartier q
                  JOIN q.commune c";


        $query = $this->getEntityManager()
            ->createQuery($dql);

        return $query;
    }
    public function findAll(){

        $query = $this->getMainQuery();
        return $query->getArrayResult();
    }

}
