<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    use UtilForRepository;
    private function getMainDql(){
        $dql  = "SELECT PARTIAL u.{id,username,nom,prenom},ur,r,q,c
                 FROM AppBundle:User u
                 LEFT JOIN u.userRestaurant ur
                 LEFT JOIN ur.restaurant r
                 LEFT JOIN r.quartier q
                 LEFT JOIN q.commune c";
        return $dql;
    }
    public function findAll(){

        $dql = $this->getMainDql();
        return $this->fillParameterAndGetResult($dql);
    }

}
