# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.operation:
        class: AppBundle\Util\Operation
        arguments: ["@doctrine.orm.entity_manager","@validator"]

    app.api.exception.subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_subscriber }

    app.commande.subscriber:
        class: AppBundle\EventListener\CommandeSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.api.jwt.subscriber:
        class: AppBundle\EventListener\JWTSubscriber
        arguments: ["@serializer"]
        tags:
            - { name: kernel.event_subscriber }

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    neema.namer:
        class: AppBundle\Naming\Namer



