# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    majoration_time_livraison: "%majorationtimelivraison%"

services:
    app.commande.manager:
        class: AppBundle\Service\CommandeManager
        arguments: ["%majoration_time_livraison%"]

    app.operation:
        class: AppBundle\Util\Operation
        arguments: ["@doctrine.orm.entity_manager","@validator"]

    app.user_neema.provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine.orm.entity_manager"]

    app.api.exception.subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_subscriber }

    app.commande.subscriber:
        class: AppBundle\EventListener\CommandeSubscriber
        arguments: ["@doctrine.orm.entity_manager","@app.commande.manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.livraison.subscriber:
        class: AppBundle\EventListener\LivraisonSubscriber
        arguments: ["@doctrine.orm.entity_manager","@app.commande.manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.livreur.subscriber:
        class: AppBundle\EventListener\LivreurSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.api.jwt.subscriber:
        class: AppBundle\EventListener\JWTSubscriber
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: kernel.event_subscriber }

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    neema.namer:
        class: AppBundle\Naming\Namer

    app.restaurant_is_allow:
        class: AppBundle\EventListener\RestaurantIsAllowListener
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        tags:
            - { name: kernel.event_subscriber }




