<?php

namespace AppBundle\Repository;

/**
 * LieuLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LieuLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
