<?php

namespace AppBundle\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends \Doctrine\ORM\EntityRepository
{

    private function minQueryBuilder(){
        $queryBuilder = $this->createQueryBuilder('n');
        return $queryBuilder;
    }

    public function findByUser($id){
        $notifications = $this->minQueryBuilder()
            ->leftJoin('n.user','u')
            ->where('u.id=:id')
            ->setParameter('id',$id)
            ->getQuery()
            ->getArrayResult();

        return $notifications;
    }

}
