<?php

namespace AppBundle\Repository;

/**
 * NumeroAutoriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NumeroAutoriseRepository extends \Doctrine\ORM\EntityRepository
{
}
