<?php

namespace AppBundle\Repository;

/**
 * TypeCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
