gesdinet_jwt_refresh_token:
    path:     /api/users/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

