# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html

services:
    app.commande.manager:
        class: AppBundle\Service\CommandeManager
        arguments: ["@doctrine.orm.entity_manager","%timeMarge%","%timeLivraison%","@app.util.service","@validator","@security.token_storage","@event_dispatcher"]

    app.util.service:
        class: AppBundle\Service\UtilService
        arguments: ["@doctrine.orm.entity_manager"]

    app.livreur.service:
        class: AppBundle\Service\LivreurService
        arguments: ["@doctrine.orm.entity_manager","@app.commande.manager"]

    app.livraison.service:
        class: AppBundle\Service\LivraisonService
        arguments: ["@doctrine.orm.entity_manager","@app.livreur.service","@app.commande.manager","%fraisCommande%","@app.rabbitmq"]

    app.plat.service:
        class: AppBundle\Service\PlatService
        arguments: ["@doctrine.orm.entity_manager"]

    app.restaurant.service:
        class: AppBundle\Service\RestaurantService
        arguments: ["@doctrine.orm.entity_manager"]

    app.rabbitmq:
        class: AppBundle\Service\RabbitMQService
        arguments: ["@old_sound_rabbit_mq.notification_producer"]

    app.operation:
        class: AppBundle\Util\Operation
        arguments: ["@doctrine.orm.entity_manager","@validator"]

    app.user_neema.provider:
        class: AppBundle\Security\UserProvider
        arguments: ["@doctrine.orm.entity_manager"]

    app.api.exception.subscriber:
        class: AppBundle\EventListener\ApiExceptionSubscriber
        tags:
            - { name: kernel.event_subscriber }

    app.request.subscriber:
        class: AppBundle\EventListener\RequestSubscriber
        arguments: ["@kernel"]
        tags:
            - { name: kernel.event_subscriber }

    app.controller.subscriber:
        class: AppBundle\EventListener\ControllerSubscriber
        arguments: ["@security.token_storage"]
        tags:
            - { name: kernel.event_subscriber }

    app.commande.subscriber:
        class: AppBundle\EventListener\CommandeSubscriber
        arguments: ["@doctrine.orm.entity_manager","@app.commande.manager","@app.rabbitmq","@app.livreur.service","@app.livraison.service"]
        tags:
            - { name: kernel.event_subscriber }

    app.livraison.subscriber:
        class: AppBundle\EventListener\LivraisonSubscriber
        arguments: ["@doctrine.orm.entity_manager","@app.commande.manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.livreur.subscriber:
        class: AppBundle\EventListener\LivreurSubscriber
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_subscriber }

    app.api.jwt.subscriber:
        class: AppBundle\EventListener\JWTSubscriber
        arguments: ["@security.authorization_checker"]
        tags:
            - { name: kernel.event_subscriber }

    jwt_token_authenticator:
        class: AppBundle\Security\JwtTokenAuthenticator
        autowire: true

    neema.namer:
        class: AppBundle\Naming\Namer

    app.restaurant_is_allow:
        class: AppBundle\EventListener\RestaurantIsAllowListener
        arguments: ["@doctrine.orm.entity_manager","@security.token_storage"]
        tags:
            - { name: kernel.event_subscriber }




